[project]
name = "reproducr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.5",
    "sqlite-utils>=3.39",
    "urllib3>=2.6.3",
]
